name: Deploy SalesAnalysis to IIS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o publish --runtime win-x64 --self-contained false

    - name: Deploy to IIS
      run: |
        xcopy publish C:\inetpub\wwwroot\SalesPrediction /E /I /Y
        iisreset
