name: Build and Deploy to IIS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o publish

    - name: Deploy to IIS
      run: |
        net stop w3svc
        robocopy publish C:\inetpub\wwwroot\SalesPrediction /E /MIR
        net start w3svc
